### ISSUE TITLE
Compilation of bdFoam

### ISSUE THREAD

**Issue by asela326** [NREL/BioReactorDesign#32]
How to compile bdoFoam ? could this be explained 

Which version of OpenFOAM is needed  ? 9 or 6?

Where exactly to put the bdoFoam and multiphaseEulerFoam in the OpenFOAM folder structure?

Thanks.

**Comment by malihass** [comment]
Hi, thanks for the opening this issue.
We are in the process or harmonizing all these tools to work with a single open foam version (openfoam9)
Right now, bdoFoam can only compile with OpenFOAM 6 :-( 
MultiphaseEulerFoam requires OpenFOAM 9

for bdoFoam, you need to copy the entire  `BioReactorDesign/main/OFsolvers/applications/bdoFoam` in `$FOAM_APP/solvers` 
 
for multiphaseEulerFoam, the short answer is to copy the files to `$FOAM_APP/solvers/multiphase/` . However you'll notice that `$FOAM_APP/solvers/multiphase/multiphaseEulerFoam` contains a lot of folders. We have only added modifs in some of the folders. What you need to do is copy the files available under `BioReactorDesign/main/OFsolvers/applications/multiphaseEulerFoam` in the tree structure of ` $FOAM_APP/solvers/multiphase/multiphaseEulerFoam`

It might be good to add a script that does this operation so that future users don't have the same issue. If you want to open a PR and add that to the repo, that would be very much appreciated !

**Comment by hsitaram** [comment]
Hi

If you havent already seen the workings of bdofoam, it is in this paper: https://www.sciencedirect.com/science/article/pii/S0263876223004689

bdofoam was written using ofoam 6. If you have a compiled version, copy the reactingEulerFoam folder (OpenFOAM-dev/applications/solvers/multiphase/reactingEulerFoam) to your desired location, say home.
1) copy bdofoam into this folder
2) change this line bdoFoam/Make/files to use USER_APPBIN instead of APPBIN  (EXE = $(FOAM_USER_APPBIN)/bdoFoam)
3) do wmake inside bdofoam, now you should have an executable in your home directory in say:
/home/<yourname>/OpenFOAM/<yourname>-dev/platforms/linux64GccDPInt32Opt/bin

I will post a test case today, you can try it out with that

**Comment by hsitaram** [comment]
@asela326  - I have updated the main branch with two test cases now in BioReactorDesign/OFsolvers/tutorial_cases/bdofoam_cases. Hope you are able to build and run it.

**Comment by malihass** [comment]
@asela326 Please let us know if this solves the issue

**Comment by asela326** [comment]
Hi, 
Yes once the bdFoam is inside reactingEulerFoam it compiles on OF6. Thanks.
